#!/bin/bash
set -ex
# shellcheck source=./ci/test/common
source ./common
init_test_repo
cd "$test_repo_path"

cat <<EOF > main.workflow
workflow "test" {
  resolves = "show env"
}

action "show env" {
  uses = "actions/bin/sh@master"
  args = "ls"
}
EOF

popper run

docker ps -a | grep 'show_env'

docker cp ./main.workflow show_env:/

popper run --reuse

# the file we copied above should still be there
docker cp show_env:/main.workflow main.workflow

# now we re-run without --reuse so a new container is created
popper run

# so the file shouldn't be there
! docker cp show_env:/main.workflow /tmp/main.workflow

# lastly, test reuse for a single action
popper run --reuse 'show env'


# check for persistence of files written during runtime
cat <<EOF > main.workflow
workflow "test" {
  resolves = "show env"
}

action "show env" {
  uses = "actions/bin/sh@master"
  args = ["echo 'Its Working..' > /test.file"]
}
EOF

popper run --runtime "$RUNTIME"

cat <<EOF > main.workflow
workflow "test" {
  resolves = "show env"
}

action "show env" {
  uses = "actions/bin/sh@master"
  args = ["cat /test.file"]
}
EOF

popper run --reuse --runtime "$RUNTIME" > output
grep -q "Its Working.." output

# test while reusing the container uses the updated args.
cat <<EOF > main.workflow
workflow "test" {
  resolves = "show env"
}

action "show env" {
  uses = "actions/bin/sh@master"
  args = "ls"
  env = {
    TOOL_NAME="popper"
  }
}
EOF

popper run --runtime "$RUNTIME" > output
grep -q "README.md" output
grep -q "main.workflow" output


cat <<EOF > main.workflow
workflow "test" {
  resolves = "show env"
}

action "show env" {
  uses = "actions/bin/sh@master"
  args = ["echo \$TOOL_NAME"]
}
EOF

popper run --reuse --runtime "$RUNTIME" > output
grep  -q "popper" output
! grep -q "README.md" output
! grep -q "main.workflow" output

echo "Test REUSE passed."
