---
dist: xenial
language: python
python:
- "2.7"
- "3.7"
services: docker
before_install:
- sudo apt-get update
- wget http://neurodeb.pirsquared.org/pool/main/s/singularity-container/singularity-container_2.6.1-2~nd16.04+1_amd64.deb
- sudo apt-get -f install ./singularity-container_2.6.1-2~nd16.04+1_amd64.deb
- wget https://releases.hashicorp.com/vagrant/2.2.4/vagrant_2.2.4_x86_64.deb
- sudo apt-get -f install ./vagrant_2.2.4_x86_64.deb
- pip install git+https://github.com/virtuald/pyhcl.git@0.3.12#egg=pyhcl
- pip install git+https://github.com/JayjeetAtGithub/python-vagrant.git#egg=python-vagrant
install:
- pip install cli/
script:
- popper run --recursive
