---
dist: xenial
language: python
python:
- "2.7"
- "3.7"
env:
- RUNTIME=singularity POPPER_TEST_MODE=with-git
- RUNTIME=singularity POPPER_TEST_MODE=without-git
- RUNTIME=docker POPPER_TEST_MODE=with-git
- RUNTIME=docker POPPER_TEST_MODE=without-git
services: docker
before_install:
- sudo apt-get update
- sudo apt-get install -y build-essential libssl-dev uuid-dev libgpgme11-dev libseccomp-dev pkg-config squashfs-tools
- mkdir -p ${GOPATH}/src/github.com/sylabs
- cd ${GOPATH}/src/github.com/sylabs
- git clone https://github.com/sylabs/singularity.git
- cd singularity
- git checkout v3.2.0
- cd ${GOPATH}/src/github.com/sylabs/singularity
- ./mconfig
- cd ./builddir
- make
- sudo make install
- singularity version
- cd $TRAVIS_BUILD_DIR
- pip install git+https://github.com/virtuald/pyhcl.git@0.3.12#egg=pyhcl
install:
- pip install cli/
script:
- popper run
